# Generated by Django 5.1.2 on 2025-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_nullable_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="matchgroup",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
