# Generated by Django 5.1.2 on 2025-04-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_user"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personrecord",
            name="main_person_sha256_2ea0dc_idx",
        ),
        migrations.AlterField(
            model_name="personrecord",
            name="sha256",
            field=models.BinaryField(unique=True),
        ),
    ]
