# Generated by Django 5.1.2 on 2025-06-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_personrecord_main_person_sha256_2ea0dc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="s3_uri",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="source_uri",
            field=models.TextField(null=True),
        ),
    ]
