# Generated by Django 5.1.2 on 2025-09-21 22:39

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor



def enable_unaccent_extension(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Enable unaccent extension if possible, otherwise log a warning."""
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")
        except Exception as e:
            print(f"Warning: Could not create unaccent extension: {e}")
            print("Please ask your database administrator to run: CREATE EXTENSION unaccent;")


def disable_unaccent_extension(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Disable unaccent extension."""
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("DROP EXTENSION IF EXISTS unaccent CASCADE;")
        except Exception as e:
            print(f"Warning: Could not drop unaccent extension: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_allow_null_text_fields'),
    ]

    operations = [
        migrations.RunPython(enable_unaccent_extension, disable_unaccent_extension),
    ]
