# Generated by Django 5.1.2 on 2025-09-21 22:39
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_allow_null_text_fields"),
    ]

    operations = [
        CreateExtension("unaccent"),
    ]
