apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuva-empi-backend-dev
  labels:
    app: tuva-empi-backend-dev
spec:
  selector:
    matchLabels:
      app: tuva-empi-backend-dev
  template:
    metadata:
      labels:
        app: tuva-empi-backend-dev
    spec:
      serviceAccountName: tuva-empi-backend-dev
      containers:
        - name: tuva-empi-backend-dev
          image: tuva-empi-backend-dev:latest
          imagePullPolicy: Never
          command: ["sleep"]
          args: ["infinity"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: 1000M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
