name: Build Backend
on:
  workflow_call:
    inputs:
      push_image:
        type: boolean
        default: false
        required: false
      image_name:
        type: string
        required: false
      image_tag:
        type: string
        required: false
    secrets:
      REGISTRY_TOKEN:
        required: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      if: inputs.push_image
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: ${{ inputs.push_image }}
        tags: ${{ inputs.push_image && format('{0}:{1}', inputs.image_name, inputs.image_tag) || github.sha }}
