name: Build Backend
on:
  pull_request: {}
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      run: |
        cd backend && docker build -t ${{ github.sha }} .
