name: Test Docs

on:
  pull_request:
    paths:
      - docs/**
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  test:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'npm'

      - name: Install
        run: |
          npm install

      - name: Build and lint
        run: |
          npm run lint
          npm run build
